package router

import (
	"net/http"
	"os"
	"strings"
	"time"

	cors "github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
	serverHandler "github.com/qinyilin/go-agent/internal/server/handler"
	"github.com/qinyilin/go-agent/internal/server/middleware"

	// swagger
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	// project swagger docs (generated by: swag init -g cmd/server/main.go -o internal/server/docs)
	_ "github.com/qinyilin/go-agent/internal/server/docs"
)

type RouterConfig struct {
	ReportHandler        *serverHandler.ReportHandler
	WSHandler            *serverHandler.WSHandler
	ControlHandler       *serverHandler.ControlHandler
	SnapshotHandler      *serverHandler.DeviceSnapshotHandler
	DevicesHandler       *serverHandler.DevicesHandler
	RiskWhitelistHandler *serverHandler.RiskWhitelistHandler
	AssetsSearchHandler  *serverHandler.AssetsSearchHandler
}

func NewRouter(cfg RouterConfig) *gin.Engine {
	if cfg.ReportHandler == nil || cfg.WSHandler == nil || cfg.SnapshotHandler == nil || cfg.DevicesHandler == nil {
		panic("router: nil handlers")
	}

	r := gin.New()
	r.Use(middleware.RequestID())
	r.Use(middleware.Recover())

	// CORS for browser-based frontend (e.g. Vite dev server).
	// Default: allow all origins to simplify LAN development (access via IP).
	// To restrict in production, set CORS_ORIGINS="http://host1:5173,http://host2".
	if v := strings.TrimSpace(os.Getenv("CORS_ORIGINS")); v != "" {
		allowed := strings.Split(v, ",")
		for i := range allowed {
			allowed[i] = strings.TrimSpace(allowed[i])
		}
		r.Use(cors.New(cors.Config{
			AllowOrigins:     allowed,
			AllowMethods:     []string{"GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"},
			AllowHeaders:     []string{"Origin", "Content-Type", "Authorization"},
			AllowCredentials: false,
			MaxAge:           12 * time.Hour,
		}))
	} else {
		// Allow any origin (including http://<LAN-IP>:5173) when no explicit list provided.
		r.Use(cors.New(cors.Config{
			AllowOrigins:     []string{"*"},
			AllowMethods:     []string{"GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"},
			AllowHeaders:     []string{"Origin", "Content-Type", "Authorization"},
			AllowCredentials: false,
			MaxAge:           12 * time.Hour,
		}))
	}

	// Basic health for orchestration.
	r.GET("/healthz", func(c *gin.Context) {
		c.JSON(http.StatusOK, gin.H{"status": "ok"})
	})

	// Backward-compatible ingest endpoint.
	// The agent's default demo/debug URL commonly posts to "/ingest".
	// We reuse the same batch parsing logic as POST /api/v1/report.
	r.POST("/ingest", middleware.GzipBodyDecompressor(32<<20), cfg.ReportHandler.HandleReport)

	// Swagger UI
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	api := r.Group("/api/v1")
	{
		api.POST("/report", middleware.GzipBodyDecompressor(32<<20), cfg.ReportHandler.HandleReport)
		api.GET("/device/:device_id/snapshot", cfg.SnapshotHandler.HandleSnapshot)
		api.GET("/devices", cfg.DevicesHandler.HandleDevices)
		if cfg.AssetsSearchHandler != nil {
			api.GET("/assets/search", cfg.AssetsSearchHandler.SearchSoftwareAssets)
			api.GET("/assets/software/summary", cfg.AssetsSearchHandler.GetSoftwareSummary)
			api.GET("/assets/software/find", cfg.AssetsSearchHandler.FindSoftwareDevices)
		}
		if cfg.RiskWhitelistHandler != nil {
			api.GET("/device/:device_id/risk_whitelist", cfg.RiskWhitelistHandler.GetDeviceRiskWhitelist)
			api.POST("/device/:device_id/risk_whitelist", cfg.RiskWhitelistHandler.PostDeviceRiskWhitelist)
		}
		if cfg.ControlHandler != nil {
			api.POST("/control/:device_id", cfg.ControlHandler.PostControlCommand)
			api.POST("/control/notify", cfg.ControlHandler.PostBatchNotify)
		}
	}

	// Subscribe by device_id.
	// Example: ws://host/ws/{device_id}
	r.GET("/ws/:device_id", cfg.WSHandler.HandleWS)
	if cfg.ControlHandler != nil {
		r.GET("/control/ws/:device_id", cfg.ControlHandler.HandleControlWS)
	}

	return r
}
